### ISSUE TITLE
Would like to support Adafruit nrf52840 feather express

### ISSUE THREAD

**Issue by Akirakato1** [TMRh20/TMRpcm#120]
Hi,

I found your library through a tutorial that uses Arduino uno. I'm using nrf52840 and would like to port it for that board. What things should I change or look into research to make your library compatible with the board?

Thanks,
Akira

**Comment by TMRh20** [comment]
Well the first thing to look at would be of course the datasheet for the device, so you can get a good understanding of the capabilities, along with registers & settings for timers, pwm and ADC.

The next thing to consider is overall functionality etc, and related libraries. I have created two audio libraries, TMRpcm and Aaaudio, and I would suggest that you take a look at Aaaudio instead of TMRpcm. It is more of a general audio library, providing a simpler interface to control DAC/PWM, ADC, and timers, and allows users to create a wide range of audio applications instead of only playing or recording wav files.

The next thing would be to look around for existing audio examples for the nrf52 so you can make things easier on yourself by borrowing code snippets etc.

I would start by creating an Arduino sketch that plays a simple audio file or something, get your functionality and layout down, then convert it to a library.

Peace, 
TMRh20
