### ISSUE TITLE
need library returning values on call/serial print

### ISSUE THREAD

**Issue by bryanmc1988** [TMRh20/TMRpcm#13]
so i just wanted to say that 

tmrpcm.volume();

tmrpcm.quality();

tmrpcm.loop();

etc etc for all the commands need to give a value for example 

tmrpcm.volume(); or tmrpcm.setvolume(); need to give a value so that a user can is if statements on them...

like if set volume can only be at 7 max... and volume is the control for up and down... it should let you know if the volume is at level 0 or at like 5 or level 7 so that a user can make a function that wont exceed the max or min value...

currently if you use volume(1); // controls volume up... it will keep going up till its muted it self and even if you do volume(0); it will still 

same for quality and loop and all the other lib, itshould give a value of where its at so that if statements can be used with them..

**Comment by gamecompiler** [comment]
Please rewrite your issue, ive got many problems reading that. Im sorry.
If id understood you correctly, you want states to  be returned to determine if errors did occur?
If youre makeing an overflow, its your fault, you can easily check with if sentences if the maximum is exceeded or not,

To check if "volumevalue" is NOT between 0 - 7.

'''

if(volume >= 0 || volume <= 7) {
  //Everything is fine
}
else {
  //or not
}

'''

Im sure you now that. 
Im closing this now, this issue is quite old.
