### ISSUE TITLE
Slow Audio Playback

### ISSUE THREAD

**Issue by RobertDowns** [TMRh20/TMRpcm#36]
I have tried using TMRpcm with a Catalex micro sd reader. I converted the wav to a couple of different sample frequencies and they have been done at 8 bit, I can get the sound file to play, but it does so slowly, so the speech is slowed down by at least a factor of two or more?

Any ideas on what I've done wrong?

cheers
Rob

**Comment by TMRh20** [comment]
They need to be both 8-bit and mono. Sample rates between 8-32khz should be picked up automatically, so that is generally not an issue. I would guess that you have 'double samples' or something, as you would with 16-bit or stereo audio.

The [wiki](https://github.com/TMRh20/TMRpcm/wiki) has a quick step by step for audacity or iTunes that should work.

**Comment by RobertDowns** [comment]
Stereo audio it was. Working perfectly now.

Cheers

**Comment by hosjiu1702** [comment]
I will explain more @RobertDowns's idea.
In pcmConfig.h file uncomment #define STEREO_OR_16BIT
