### ISSUE TITLE
Explanation of 'complimentary mode'

### ISSUE THREAD

**Issue by gdhgdhgdh** [TMRh20/TMRpcm#42]
Hullo :)

Can you explain what the 'complimentary mode' is for? I see it referenced in the Advanced Usage page and on the wiki but can't see its actual purpose.

Cheers,
Gavin.

**Comment by TMRh20** [comment]
2 pins (speaker) = push / push (not complimentary)

2 pins (speaker) = push / pull (complimentary)

Sent from my iPod

On 2016-03-24, at 9:06 PM, gdhgdhgdh <notifications@github.com> wrote:

Hullo :)

Can you explain what the 'complimentary mode' is for? I see it referenced
in the Advanced Usage page and on the wiki but can't see its actual purpose.

Cheers,
Gavin.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/TMRh20/TMRpcm/issues/42>

**Comment by gdhgdhgdh** [comment]
Thanks for that - I still don't really get it. I understand that better volume from the speaker will be achieved by having outputting both positive and negative voltages so the cone travels further.

In Push/Pull mode, are two output pins being manipulated to deliver this setup (instead of a typical single pin and GND) ?

**Comment by TMRh20** [comment]
That is exactly it, one speaker pin to ground == push/null & with 2 pins
each pin can be positive or negative so is push/push.

Sent from my iPod

On 2016-03-26, at 4:07 PM, gdhgdhgdh <notifications@github.com> wrote:

Thanks for that - I still don't really get it. I understand that better
volume from the speaker will be achieved by having outputting both positive
and negative voltages so the cone travels further.

In Push/Pull mode, are two output pins being manipulated to deliver this
setup (instead of a typical single pin and GND) ?

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/TMRh20/TMRpcm/issues/42#issuecomment-201939898>

**Comment by TMRh20** [comment]
oops, meant push/pull instead of push push for clarity.

Sent from my iPod

On 2016-03-26, at 7:55 PM, TMRh20Projects <tmrh20@gmail.com> wrote:

That is exactly it, one speaker pin to ground == push/null & with 2 pins
each pin can be positive or negative so is push/push.

Sent from my iPod

On 2016-03-26, at 4:07 PM, gdhgdhgdh <notifications@github.com> wrote:

Thanks for that - I still don't really get it. I understand that better
volume from the speaker will be achieved by having outputting both positive
and negative voltages so the cone travels further.

In Push/Pull mode, are two output pins being manipulated to deliver this
setup (instead of a typical single pin and GND) ?

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/TMRh20/TMRpcm/issues/42#issuecomment-201939898>
