### ISSUE TITLE
Loud "pop" at the beginning and end of recording

### ISSUE THREAD

**Issue by karanbole** [TMRh20/TMRpcm#43]
First of all, cheers to all of the contribs for making an awesome library for the Arduino ! This is really cool.

Now, I would like to push my UNO a little bit by using it to record an audio source through an analog input. When recording at 22050 Hz, it sounds good enough BUT there's a loud noise at the beginning and end of file.

There's a sample attached to this post.

Did this occur to you, and do you know how I could fix this ? Thank you !
Patrick
[SAMPLE.WAV.zip](https://github.com/TMRh20/TMRpcm/files/204739/SAMPLE.WAV.zip)

**Comment by TMRh20** [comment]
Well the easy approach would probably be just discard the first & last X milliseconds of audio. Check the datasheet for info on the ADC, otherwise I'm not really sure. 

With playback, I typically would "ramp" the audio in and out to prevent clicks/pops but with our PCs that shouldn't be a problem, so it is something with the audio.
