### ISSUE TITLE
Continuous popping noise when Arduino powered via VIN

### ISSUE THREAD

**Issue by alexissantos** [TMRh20/TMRpcm#46]
When I supply power (12V or 5V) to the Arduino (an Adafruit Metro Mini) via VIN, a continuous popping sound occurs when audio is supposed to be playing, and the light on the SD card reader and the pin 13 light on the Arduino flashes along with the pop. When power is supplied over USB, audio playback works fine.

Here's a short video of the pop: https://www.youtube.com/watch?v=3xnE4kFzT7E

Any idea why this might be the case? Maybe it's a fault of [my amp](https://www.adafruit.com/product/987) and not this library?

**Comment by TMRh20** [comment]
SD cards can draw up to 200mA . The regulator is only 150mA.

Sent from my iPod

On 2016-06-05, at 8:49 AM, Alexis Santos <notifications@github.com> wrote:

When I supply power (12V or 5V) to the Arduino (an Adafruit Metro Mini) via
VIN, a continuous popping sound occurs when audio is supposed to be
playing, and the light on the SD card reader and the pin 13 light on the
Arduino flashes along with the pop. When power is supplied over USB, audio
playback works fine.

Here's a short video of the pop: https://www.youtube.com/watch?v=3xnE4kFzT7E

Any idea why this might be the case? Maybe it's a fault of my amp
<https://www.adafruit.com/product/987> and not this library?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TMRh20/TMRpcm/issues/46>, or mute the thread
<https://github.com/notifications/unsubscribe/ACfVHLxOG5-zJvc9fOFhgGxis3smoYZXks5qIuHqgaJpZM4IuXt3>
.

**Comment by alexissantos** [comment]
Aha! Just to make sure I've got this right: I've got a 2A power supply, which should be enough, but the voltage regulator on the board connected to the VIN pin is only making 150mA of it usable?

**Comment by TMRh20** [comment]
Yeah, I think so

**Comment by alexissantos** [comment]
Thanks! I'll pick up a 5V regulator to power the SD card reader.
