### ISSUE TITLE
Change playback speed.

### ISSUE THREAD

**Issue by Whyiamdead** [TMRh20/TMRpcm#47]
It`s possible to change playback speed? Very need it for my lo-fi sampler project.

**Comment by ReleaseBug** [comment]
It‘s possible, i think.
Because, this program can playback different sample rate WAV file.
That means,it can change playback speed for different sample rate WAV file.
So ...It‘s possible to change playback speed for a specified WAV file.
There are three keywords in the source code:SAMPLE_RATE,resolution,*OCRnA[tt].
Try it.
