### ISSUE TITLE
POP/Scratch noise at the start of the wav file.

### ISSUE THREAD

**Issue by CraftMarine** [TMRh20/TMRpcm#74]
Hi ! I just got my micro SD card module and I took this library to play sound file on micro SD card.

Everything is working fine exept that I have a scratchy noise at the beginning of my sound.
I've tried solution on other post but none worked :/

Here is my code:
`#include "SD.h" 
#include "TMRpcm.h" 
#include "SPI.h" 

#define SD_ChipSelectPin 4 

TMRpcm music;

void setup(){
music.speakerPin = 9; 
Serial.begin(9600); 
if (!SD.begin(SD_ChipSelectPin)){
  Serial.println("SD fail");
  return;
}
music.setVolume(5);  
music.quality(0);        
}

void loop(){
  music.play("BIP.WAV");
  delay(1000); 
}`

How can I remove this noise ?

**Comment by TMRh20** [comment]
Popping and clicking at the beginning of the file could be due to a few things, but usually the file contains metadata which is being processed as sound. This can be removed by opening the files in Audacity (free) and File->Edit Metadata->Clear  , or by enabling support for metadata by opening pcmConfig.h and uncomment ``` //#define HANDLE_TAGS ```
